### ISSUE TITLE
Not working on Android 10 (Galaxy S9+)

### ISSUE THREAD

**Issue by rodrigopiccelli** [r3bl-alliance/stay-awake-app#11]
App don't work on Android 10 on Samsung Galaxy S9+

**Comment by fkubicek** [comment]
Hello, could you please specify what isn't working for you? I have noticed problems with the automatic start when the charger is plugged in - Awake just doesn't start automatically. Are you referring to this?

**Comment by rodrigopiccelli** [comment]
Unfortunately not ... the application simply does not do its function, even enabling the option to keep the screen on it continues to shut down normally.

I'm on a Galaxy S9+ with Android 10 on it.

**Comment by fkubicek** [comment]
Oh, I see. Thanks for clearing that up. It may be caused by Samsung's changes to the OS, because it seems to work on clean Android 10. I would try making an exception for Awake, if your system has a background process killer. This is my best guess.

Unfortunately I can't help any further, because I don't know much about the backend. @nazmulidris said he was planning to rewrite parts of the app, so it could get fixed in the process.
